# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
    paths-ignore:
    - '.github/workflows/codeql.yml'
    - '.github/workflows/dependabot-auto.yml'
    - 'docs/**'
    - '*.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
    - '.github/workflows/codeql.yml'
    - '.github/workflows/dependabot-auto.yml'
    - 'docs/**'
    - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        node-version: [18.x]
        npm-parallel:
        - npm run build --if-present
        - npm run lint
        experimental: [false]
#         include:
#         - npm-parallel: npm run test:unit
#           experimental: true
#         - npm-parallel: npm run test:e2e
#           experimental: true
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: ${{ matrix.npm-parallel }}
    # - run: npm test
